sudo: required
services:
  - docker

before_install:
  - docker build -t pdcnguyen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pdcnguyen/react-test npm test -- --coverage

after_success:
  - docker build -t pdcnguyen/multi-client ./client
  - docker build -t pdcnguyen/multi-nginx ./nginx
  - docker build -t pdcnguyen/multi-server ./server
  - docker build -t pdcnguyen/multi-worker ./worker
  #Log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pdcnguyen/multi-client
  - docker push pdcnguyen/multi-nginx
  - docker push pdcnguyen/multi-server
  - docker push pdcnguyen/multi-worker